### ISSUE TITLE
校验有问题, 然后顶部横滑三个, 接着最右边向下滑到底没有反应

### ISSUE THREAD

**Issue by jasonSuzhow** [LostKe/android-GestureLock#1]

**Comment by LostKe** [comment]
因为这个demo里面的校验密码正好是这个，添加了校验成功的Toast 你看看

**Comment by jasonSuzhow** [comment]
可以了, 滑动没有反应的是因为什么原因啊

**Comment by LostKe** [comment]
@jasonSuzhow 你看看手势校验的GestureVerifyActivity这个类，校验成功其实啥也没有做，现在我加了一个Toast你可以拉下来看看，没反应正好是这种手势校验成功了。如果你需要preview中的效果可以参考我另外一个 项目 android-wuzhi
